name: breeders_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter         


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_auth: ^1.3.0
  firebase_core: ^1.3.0
  firebase_storage: ^8.1.3
  google_sign_in: ^5.0.4
  cloud_firestore: ^2.2.2
  provider: ^5.0.0
  flutter_neumorphic: ^3.1.0
  google_nav_bar: ^5.0.3
  email_validator: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_slidable: ^0.6.0
  # connectivity_plus: ^1.0.4
  group_button: ^2.2.2
  diacritic: ^0.1.3
  draggable_scrollbar: ^0.1.0
  image_picker: ^0.8.0+4
  path_provider: ^2.0.2
  google_mobile_ads: ^0.13.0
  flutter_html: ^2.1.0
  url_launcher: ^6.0.7
  flutter_markdown: ^0.6.2





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/parrot_launcher.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/icon/parrot_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/background.jpg
    - assets/image/parrot.jpg
    - assets/image/google_logo.png
    - assets/image/animal_Icon.jpg
    - assets/icon/splash.png
    #Parrots race
    - assets/image/parrotsRace/parrot_Icon.jpg
    - assets/image/parrotsRace/Aleksandretta.jpg
    - assets/image/parrotsRace/Lorysa.jpg
    - assets/image/parrotsRace/Nimfa.jpg
    - assets/image/parrotsRace/Rozella.jpg
    - assets/image/parrotsRace/Świergotka.jpg
    - assets/image/parrotsRace/Kakadu.jpg
    - assets/image/parrotsRace/Ara.jpg
    - assets/image/parrotsRace/Modrolotka.jpg
    - assets/image/parrotsRace/Łąkówka.jpg
    - assets/image/parrotsRace/Mnicha.jpg
    - assets/image/parrotsRace/Rudosterka.jpg
    - assets/image/parrotsRace/Amazonka.jpg
    - assets/image/parrotsRace/Konura.jpg
    - assets/image/parrotsRace/Barwinka.jpg
    - assets/image/parrotsRace/Nierozłączka.jpg
    - assets/image/parrotsRace/Papużka_falista.jpg
    - assets/image/parrotsRace/parrot_pair.jpg
    - assets/image/parrotsRace/Kapturnica.jpg
    - assets/image/parrotsRace/Żako.jpg
    - assets/image/parrotsRace/Lora.jpg
    - assets/image/parrotsRace/Szkarłatka.jpg
    - assets/image/parrotsRace/Afrykanka.jpg
    - assets/image/parrotsRace/Patagonka.jpg
    - assets/image/parrotsRace/Stokówka.jpg
    - assets/image/parrotsRace/Wróbliczka.jpg
    - assets/image/parrotsRace/Piona.jpg
    # Help Screens
    - assets/help/help_screen_1.png
    - assets/help/help_screen_2.png
    - assets/help/help_screen_3.png
    - assets/help/help_screen_4.png
    - assets/help/help_screen_5.png
    - assets/help/help_screen_6.png
    - assets/help/help_screen_7.png
    - assets/help/help_screen_8.png
    - assets/help/help_screen_9.png
    - assets/help/help_screen_10.png
    - assets/help/help_screen_11.png
    - assets/help/help_screen_12.png
    - assets/help/help_screen_13.png
    # policy file
    - assets/privacy_policy/
    # - assets/privacy_policy/privacy_policy.md
    # - assets/privacy_policy/terms_and_condition.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
