name: breeders_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter         


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  google_sign_in: ^4.5.3
  cloud_firestore: ^0.16.0+1
  provider: ^4.3.3
  flutter_neumorphic: ^3.0.4+1
  google_nav_bar: ^4.0.2
  email_validator: ^1.0.6
  keyboard_visibility: ^0.5.6
  auto_size_text: ^2.1.0
  flutter_slidable: ^0.5.7
  flutter_icons: ^1.1.0
  pull_to_reveal: ^0.0.2
  data_connection_checker: ^0.3.4
  group_button: ^1.3.0
  diacritic: ^0.1.1
  draggable_scrollbar_sliver: ^0.0.3
  image_picker: ^0.6.7+22
  path_provider: ^1.6.28
  google_mobile_ads: ^0.11.0
  flutter_html: ^1.2.0
  url_launcher: ^5.7.10





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/parrot_launcher.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/icon/parrot_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/background.jpg
    - assets/image/parrot.jpg
    - assets/image/google_logo.png
    - assets/image/animal_Icon.jpg
    - assets/icon/splash.png
    #Parrots race
    - assets/image/parrotsRace/parrot_Icon.jpg
    - assets/image/parrotsRace/Aleksandretta.jpg
    - assets/image/parrotsRace/Lorysa.jpg
    - assets/image/parrotsRace/Nimfa.jpg
    - assets/image/parrotsRace/Rozella.jpg
    - assets/image/parrotsRace/Świergotka.jpg
    - assets/image/parrotsRace/Kakadu.jpg
    - assets/image/parrotsRace/Ara.jpg
    - assets/image/parrotsRace/Modrolotka.jpg
    - assets/image/parrotsRace/Łąkówka.jpg
    - assets/image/parrotsRace/Mnicha.jpg
    - assets/image/parrotsRace/Rudosterka.jpg
    - assets/image/parrotsRace/Amazonka.jpg
    - assets/image/parrotsRace/Konura.jpg
    - assets/image/parrotsRace/Barwinka.jpg
    - assets/image/parrotsRace/Nierozłączka.jpg
    - assets/image/parrotsRace/Papużka_falista.jpg
    - assets/image/parrotsRace/parrot_pair.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
